WIP: webserv: Almost finished

diff --git a/wip/webserv/Makefile b/wip/webserv/Makefile
--- a/wip/webserv/Makefile
+++ b/wip/webserv/Makefile
@@ -3,99 +3,119 @@
 #                                                         :::      ::::::::    #
 #    Makefile                                           :+:      :+:    :+:    #
 #                                                     +:+ +:+         +:+      #
-#    By: ecaceres <marvin@42.fr>                    +#+  +:+       +#+         #
+#    By: alicetetu <alicetetu@student.42.fr>        +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
 #    Created: 2019/08/13 15:11:33 by ecaceres          #+#    #+#              #
-#    Updated: 2019/08/13 15:11:34 by ecaceres         ###   ########.fr        #
+#    Updated: 2020/11/30 16:18:47 by alicetetu        ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
-PROJECT_ROOT			= $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
+USE_FSANITIZE			= false
+RUN_TESTS				= 0
+DO_MAKE_RE				= 0
+RUN_WITH_VALGRIND		= 0
+SIEGE_URL				= host.docker.internal
+SIEGE_FILE				= /wordpress/
+ARGS					=
+VALGRIND_ARGS			=
 
-COLOR_RESET				= \033[0m
-COLOR_LIGHT_GREEN		= \033[92m
-COLOR_LIGHT_YELLOW		= \033[93m
-COLOR_LIGHT_MAGENTA		= \033[95m
-COLOR_WHITE				= \033[97m
+SOURCE_DIR				= source
+PROJECT_MAKE			= make -s -C $(SOURCE_DIR) USE_FSANITIZE=$(USE_FSANITIZE) RUN_TESTS=$(RUN_TESTS)
 
-FIX_SOURCE_EXT			= cpp
-FIX_HEADER_EXT			= h
-FIX_GO_DEEPER			= true
-FIX_SOURCES_DIR			= .
-FIX_HEADERS_DIR			= .
-FIX_LIBRARIES_DIR		= .
+ifeq ($(shell if grep -q Microsoft /proc/version 2>/dev/null; then echo "wsl"; else echo "linux"; fi),wsl)
+    DOCKER := /mnt/c/Windows/System32/cmd.exe /c docker
+else
+    DOCKER := docker
+endif
 
-TARGET					= webserv
-SOURCES					= ./util/options/OptionParser.cpp ./util/options/Option.cpp ./util/unit/DataSize.cpp ./util/unit/DataUnit.cpp ./util/Closable.cpp ./util/Logger.cpp ./config/Configuration.cpp ./config/block/ServerBlock.cpp ./config/block/LocationBlock.cpp ./config/block/CGI.cpp ./io/Socket.cpp ./io/SocketServer.cpp ./webserv.cpp ./server/WebServer.cpp ./http/HTTPMethod.cpp ./http/HTTPOrchestrator.cpp ./http/HTTPServer.cpp ./http/HTTPHeaderFields.cpp ./http/HttpResponse.cpp ./http/HTTP.cpp ./http/mime/MimeRegistry.cpp ./http/mime/Mime.cpp ./http/HTTPDate.cpp ./http/HttpRequestParser.cpp ./http/HTTPStatus.cpp ./http/HTTPVersion.cpp ./http/HttpRequest.cpp ./exception/Exception.cpp ./exception/IOException.cpp ./exception/IllegalArgumentException.cpp
-HEADERS					= 
-LIBRARIES				= 
-LIBRARIES_BIN			= 
-
-OBJECTS					= $(SOURCES:.cpp=.o)
-
-COMPILER				= g++
-
-FRAMEWORKS				= 
-FLAGS					= -g3 # -fsanitize=address
-TARGET_REQUIRED_FLAGS	= -I.
-
-TOOL_BASE64_DECODE		= base64 -D
-
-MAKE_PREFIX				= "$(COLOR_LIGHT_MAGENTA)[$(COLOR_LIGHT_GREEN) make: $(TARGET) $(COLOR_LIGHT_MAGENTA)]"
-
-.cpp.o:
-	@echo $(MAKE_PREFIX) "$(COLOR_WHITE)Compiling: $(COLOR_LIGHT_YELLOW)$<$(COLOR_RESET)"
-	@${COMPILER} ${FLAGS} $(TARGET_REQUIRED_FLAGS) -c $< -o ${<:.cpp=.o}
-
-$(TARGET): ${OBJECTS}
-	@if [ "$(LIBRARIES)" != "" ]; then make $(LIBRARIES); fi;
-	@echo $(MAKE_PREFIX) "$(COLOR_WHITE)Compiling target: $(COLOR_LIGHT_YELLOW)$(TARGET)$(COLOR_RESET)"
-	@${COMPILER} ${FLAGS} $(TARGET_REQUIRED_FLAGS) $(foreach framework,$(FRAMEWORKS),-framework $(framework)) $(LIBRARIES_BIN) $(OBJECTS) -o $(TARGET)
-
-all: $(TARGET)
+all: --touch-test-files
+	@$(PROJECT_MAKE) all
     
-fclean: clean
-	@echo $(MAKE_PREFIX) "$(COLOR_WHITE)Removed target$(COLOR_RESET)"
-	@rm -f $(TARGET)
+fclean:
+	@$(PROJECT_MAKE) fclean
     
 clean:
-	@echo $(MAKE_PREFIX) "$(COLOR_WHITE)Removed objects$(COLOR_RESET)"
-	@rm -f $(OBJECTS)
-	@rm -f $(LIBRARIES_BIN)
-	@rm -f gather.py updater.py find_libs.py find_libs_bin.py
+	@$(PROJECT_MAKE) clean
     
-re: fclean all
-
-$(LIBRARIES):
-	@echo $(MAKE_PREFIX) "$(COLOR_WHITE)Compiling library: $(COLOR_LIGHT_YELLOW)$@$(COLOR_RESET)"
-	@make -C $@
-	@cp -f $$(ls $(foreach bin,$(LIBRARIES_BIN),$@/$(bin)) 2> /dev/null || true) .
+re:
+	@$(PROJECT_MAKE) re
+    
+rej:
+	@$(PROJECT_MAKE) fclean
+	@$(PROJECT_MAKE) all -j $(shell nproc)
 
 norm:
-	@echo $(MAKE_PREFIX) "$(COLOR_WHITE)Calling the norminette...$(COLOR_RESET)"
-	@norminette $(SOURCES) $(HEADERS)
-	
-gather.py:
-	@echo "aW1wb3J0IG9zDQppbXBvcnQgc3lzDQoNCg0KZGVmIGV4cGxvcmUocGF0aCwgZXh0ZW5zaW9ucywgZ29fZGVlcGVyPUZhbHNlKToNCiAgICBmaWxlcyA9IFtdDQogICAgDQogICAgZm9yIGZpbGUgaW4gb3MubGlzdGRpcihwYXRoKToNCiAgICAgICAgZmlsZSA9IG9zLnBhdGguam9pbihwYXRoLCBmaWxlKQ0KICAgICAgICANCiAgICAgICAgaWYgb3MucGF0aC5pc2ZpbGUoZmlsZSk6DQogICAgICAgICAgICBpZiBsZW4oZXh0ZW5zaW9ucykgIT0gMCBhbmQgb3MucGF0aC5zcGxpdGV4dChmaWxlKVsxXVsxOl0gbm90IGluIGV4dGVuc2lvbnM6DQogICAgICAgICAgICAgICAgY29udGludWUNCiAgICAgICAgICAgIA0KICAgICAgICAgICAgZmlsZXMuYXBwZW5kKGZpbGUpDQogICAgICAgIGVsc2U6DQogICAgICAgICAgICBpZiBnb19kZWVwZXI6DQogICAgICAgICAgICAgICAgZmlsZXMuZXh0ZW5kKGV4cGxvcmUoZmlsZSwgZXh0ZW5zaW9ucywgZ29fZGVlcGVyKSkNCiAgICANCiAgICByZXR1cm4gZmlsZXMNCg0KDQphcmd2ID0gc3lzLmFyZ3YNCmFyZ2MgPSBsZW4oYXJndikNCg0KaWYgYXJnYyA8IDI6DQogICAgcHJpbnQoInVzYWdlOiB7fSBwYXRoIFsgZXh0ZW5zaW9ucyAuLi4gXSBbIGdvX2RlZXBlciAoYm9vbCkgXSIuZm9ybWF0KGFyZ3ZbMF0pKQ0KICAgIGV4aXQoMSkNCg0KZXh0ZW5zaW9ucyA9IFsgZXh0ZW5zaW9uLnJlcGxhY2UoIi4iLCAiIikgZm9yIGV4dGVuc2lvbiBpbiBhcmd2WzI6XSBdDQpnb19kZWVwZXIgPSBUcnVlDQoNCmlmIGxlbihleHRlbnNpb25zKSAhPSAwOg0KICAgIGxhc3QgPSBleHRlbnNpb25zW2xlbihleHRlbnNpb25zKSAtIDE6XVswXQ0KICAgIA0KICAgIGlmIGxhc3QgaW4gWyAiMCIsICIxIiwgInRydWUiLCAiZmFsc2UiIF06DQogICAgICAgIGdvX2RlZXBlciA9IGxhc3QgaW4gWyAiMSIsICJ0cnVlIiBdDQogICAgICAgIGV4dGVuc2lvbnMgPSBleHRlbnNpb25zWzpsZW4oZXh0ZW5zaW9ucykgLSAxXQ0KDQpmaWxlcyA9IGV4cGxvcmUoYXJndlsxXSwgZXh0ZW5zaW9ucywgZ29fZGVlcGVyKQ0KDQpwcmludCgiICIuam9pbihmaWxlcykpDQo=" | $(TOOL_BASE64_DECODE) > gather.py
-	@echo $(MAKE_PREFIX) "$(COLOR_WHITE)Created gather.py file.$(COLOR_RESET)"
-	
-updater.py:
-	@echo "aW1wb3J0IG9zCmltcG9ydCByZQppbXBvcnQgc3lzCgphcmd2ID0gc3lzLmFyZ3YKYXJnYyA9IGxlbihhcmd2KQoKaWYgYXJnYyA8IDI6CiAgICBwcmludCgidXNhZ2U6IHt9IGtleSA8IHZhbHVlIi5mb3JtYXQoYXJndlswXSkpCiAgICBleGl0KDEpCgprZXkgPSBhcmd2WzFdCnZhbHVlID0gc3lzLnN0ZGluLnJlYWQoKS5yZXBsYWNlKCJcbiIsICIiKQoKd2l0aCBvcGVuKCJNYWtlZmlsZSIsICJyIikgYXMgZmlsZToKICAgIGNvbnRlbnQgPSBmaWxlLnJlYWQoKQogICAgCmxpbmVzID0gW10KCmZvciBsaW5lIGluIGNvbnRlbnQuc3BsaXQoJ1xuJyk6CiAgICBtYXRjaGVzID0gcmUuZmluZGl0ZXIociIiICsga2V5ICsgIihbXHRdKykuKiQiLCBsaW5lLCByZS5NVUxUSUxJTkUpCiAgICAKICAgIGZvdW5kID0gRmFsc2UKICAgIAogICAgZm9yIG1hdGNoIGluIG1hdGNoZXM6CiAgICAgICAgZm91bmQgPSBUcnVlCiAgICAgICAgCiAgICAgICAgbGluZXMuYXBwZW5kKCJ7fXt9PSB7fSIuZm9ybWF0KGtleSwgbWF0Y2guZ3JvdXAoMSksIHZhbHVlKSkKICAgICAgICAKICAgICAgICBicmVhawoKICAgIGlmIG5vdCBmb3VuZDoKICAgICAgICBsaW5lcy5hcHBlbmQobGluZSkKCndpdGggb3BlbigiTWFrZWZpbGUiLCAidyIpIGFzIGZpbGU6CiAgICBmaWxlLndyaXRlKCJcbiIuam9pbihsaW5lcykp" | $(TOOL_BASE64_DECODE) > updater.py
-	@echo $(MAKE_PREFIX) "$(COLOR_WHITE)Created updater.py file.$(COLOR_RESET)"
+	@$(PROJECT_MAKE) norm
 
-find_libs.py:
-	@echo "aW1wb3J0IG9zDQppbXBvcnQgc3lzDQoNCmFyZ3YgPSBzeXMuYXJndg0KYXJnYyA9IGxlbihhcmd2KQ0KDQppZiBhcmdjIDwgMjoNCiAgICBwcmludCgidXNhZ2U6IHt9IHBhdGgiLmZvcm1hdChhcmd2WzBdKSkNCiAgICBleGl0KDEpDQogICAgDQpsaWJyYXJpZXMgPSBbXQ0KDQpmb3IgcGF0aCBpbiBvcy5saXN0ZGlyKGFyZ3ZbMV0pOg0KICAgIGlmIG9zLnBhdGguaXNkaXIocGF0aCk6DQogICAgICAgIGlmICdNYWtlZmlsZScgaW4gb3MubGlzdGRpcihwYXRoKToNCiAgICAgICAgICAgIGxpYnJhcmllcy5hcHBlbmQocGF0aCkNCg0KcHJpbnQoIiAiLmpvaW4obGlicmFyaWVzKSkNCg==" | $(TOOL_BASE64_DECODE) > find_libs.py
-	@echo $(MAKE_PREFIX) "$(COLOR_WHITE)Created find_libs.py file.$(COLOR_RESET)"
+update:
+	@$(PROJECT_MAKE) update
 
-find_libs_bin.py:
-	@echo "aW1wb3J0IG9zDQppbXBvcnQgc3lzDQppbXBvcnQgcmUNCg0KYXJndiA9IHN5cy5hcmd2DQphcmdjID0gbGVuKGFyZ3YpDQoNClJFR0VYID0gciIoPzpOQU1FfFRBUkdFVClbIFx0XSo9WyBcdF0qKFtcdy5dKylbXHNdIg0KDQppZiBhcmdjIDwgMjoNCiAgICBwcmludCgidXNhZ2U6IHt9IHBhdGgiLmZvcm1hdChhcmd2WzBdKSkNCiAgICBleGl0KDEpDQogICAgDQpsaWJyYXJpZXMgPSBbXQ0KDQpmb3IgcGF0aCBpbiBvcy5saXN0ZGlyKGFyZ3ZbMV0pOg0KICAgIGlmIG9zLnBhdGguaXNkaXIocGF0aCk6DQogICAgICAgIG1ha2VmaWxlX3BhdGggPSBvcy5wYXRoLmpvaW4ocGF0aCwgIk1ha2VmaWxlIikNCiAgICAgICAgDQogICAgICAgIGlmIG9zLnBhdGguZXhpc3RzKG1ha2VmaWxlX3BhdGgpOg0KICAgICAgICAgICAgd2l0aCBvcGVuKG1ha2VmaWxlX3BhdGgsICJyIikgYXMgZmlsZToNCiAgICAgICAgICAgICAgICBiaW5zID0gW10NCiAgICAgICAgICAgICAgICANCiAgICAgICAgICAgICAgICBmb3IgbWF0Y2ggaW4gcmUuZmluZGl0ZXIoUkVHRVgsIGZpbGUucmVhZCgpLCByZS5NVUxUSUxJTkUpOg0KICAgICAgICAgICAgICAgICAgICBiaW5zLmFwcGVuZChtYXRjaC5ncm91cCgxKSkNCiAgICAgICAgICAgICAgICANCiAgICAgICAgICAgICAgICBpZiBsZW4oYmlucykgPT0gMDoNCiAgICAgICAgICAgICAgICAgICAgcHJpbnQoInt9IHdhcm5pbmc6IG5vIHRhcmdldCBmb3VuZCBmb3IgbGlicmFyeSB7fSIuZm9ybWF0KGFyZ3ZbMF0sIHBhdGgpKQ0KICAgICAgICAgICAgICAgICAgICBjb250aW51ZQ0KICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgIGlmIGxlbihiaW5zKSA+IDE6DQogICAgICAgICAgICAgICAgICAgIHByaW50KCJ7fSB3YXJuaW5nOiBtb3JlIHRoYW4gb25lIHRhcmdldCBmb3VuZCBmb3IgbGlicmFyeSB7fSAoe30pIi5mb3JtYXQoYXJndlswXSwgcGF0aCwgYmlucykpDQogICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgIGxpYnJhcmllcy5leHRlbmQoYmlucykNCg0KcHJpbnQoIiAiLmpvaW4obGlicmFyaWVzKSkNCg==" | $(TOOL_BASE64_DECODE) > find_libs_bin.py
-	@echo $(MAKE_PREFIX) "$(COLOR_WHITE)Created find_libs_bin.py file.$(COLOR_RESET)"
+run: RUN_TESTS=0
+run: all
+	@$(PROJECT_MAKE) ARGS="$(ARGS)" run
 
-update: gather.py updater.py find_libs.py find_libs_bin.py
-	@echo $$(python gather.py $(FIX_SOURCES_DIR) $(FIX_SOURCE_EXT) $(FIX_GO_DEEPER)) | python updater.py SOURCES
-	@echo $$(python gather.py $(FIX_HEADERS_DIR) $(FIX_HEADER_EXT) $(FIX_GO_DEEPER)) | python updater.py HEADERS
-	@echo $$(python find_libs.py $(FIX_LIBRARIES_DIR)) | python updater.py LIBRARIES
-	@echo $$(python find_libs_bin.py $(FIX_LIBRARIES_DIR)) | python updater.py LIBRARIES_BIN
-	@echo $(MAKE_PREFIX) "$(COLOR_WHITE)Makefile is now up-to-date.$(COLOR_RESET)"
+run-here: RUN_TESTS=0
+run-here: ARGS=-f source/conf4.json
+run-here: all
+	@./$(SOURCE_DIR)/webserv $(ARGS)
 
-.PHONY: all clean fclean re .c.o norm update $(LIBRARIES)
+run-with-valgrind: RUN_TESTS=0
+run-with-valgrind: all
+	@$(PROJECT_MAKE) ARGS="$(ARGS)" VALGRIND_ARGS="$(VALGRIND_ARGS)" run-with-valgrind
+
+test: RUN_TESTS=1
+test: all
+	@$(PROJECT_MAKE) ARGS="$(ARGS)" run
+
+test-configs: RUN_TESTS=0
+test-configs: all
+	@ \
+	previous=""; \
+	for f in $(SOURCE_DIR)/tests/configs/invalid-*.json; do \
+		name=$$(basename $$f .json | sed -e "s/^invalid-//"); \
+		key=$$(echo $$name | awk -F --- '{ print $$1 }'); \
+		error=$$(echo $$name | awk -F --- '{ print $$2 }'); \
+		\
+		if ! test -z "$$TERM"; then \
+			if test "$$previous" = "$$key"; then \
+				key=""; \
+			else \
+				printf "%$$(tput cols)s" | tr " " "-"; \
+				previous=$$key; \
+			fi; \
+			printf "%s \033[30G %s \033[60G" "$$key" "$$error"; \
+		else \
+			printf "%s %s -- " "$$key" "$$error"; \
+		fi; \
+		\
+		! ./$(SOURCE_DIR)/webserv -c -f $$f; \
+	done
+
+docker-build-siege:
+	@$(DOCKER) build -t siege -f docker/siege/Dockerfile .
+
+docker-build-base:
+	@$(DOCKER) build -t webserv-base -f docker/Dockerfile.base .
+
+docker-build-run: all docker-build-base
+	@$(DOCKER) build -t webserv-run -f docker/Dockerfile.run .
+
+docker-build-test: all docker-build-base
+	@$(DOCKER) build --build-arg DO_MAKE_RE=$(DO_MAKE_RE) -t webserv-test -f docker/Dockerfile.test .
+
+docker-run: docker-build-run
+	@$(DOCKER) run --rm -it -p 80:80 webserv-run $(ARGS)
+
+docker-test: docker-build-test
+	@$(DOCKER) run --rm -it -p 80:80 -e RUN_WITH_VALGRIND=$(RUN_WITH_VALGRIND) webserv-test $(ARGS)
+
+siege: docker-build-siege
+	@$(DOCKER) run --rm -it -t siege -d1 -c50 -b -i $(SIEGE_URL)$(SIEGE_FILE)
+
+--touch-test-files:
+	@#echo ${RUN_TESTS} $$(bash -c "test -f '.test'; echo $$?") # DEBUG
+	@bash -c "if [[ ('${RUN_TESTS}' = 0 && -f '.test') || ('${RUN_TESTS}' != 0 && ! -f '.test') ]]; then touch source/main.cpp source/tests/units/*.cpp; fi"
+	@bash -c "if [[ '${RUN_TESTS}' = 0 && -f '.test' ]]; then rm .test; fi"
+	@bash -c "if [[ '${RUN_TESTS}' != 0 && ! -f '.test' ]]; then touch .test; fi"
+
+.PHONY: all clean fclean re norm update run test docker
